#ifndef CAMERA_H
#define CAMERA_H

#include "vec3.h"
#include "utility.h"

class camera {
    private:
        int width;
        int height;
        point3 position;
        vec3 lookAt;
        vec3 upVector;
        double fov;
        double exposure;
        vec3 pixel00_loc;
        vec3 pixel_delta_u;
        vec3 pixel_delta_v;

        void initialise() {
            auto focal_length = 1.0;
            auto aspect_ratio = static_cast<double>(width) / height;

            // assuming the fov is 1) in degrees, 2) referring to the vertical fov
            auto viewport_height = 2 * focal_length * tan(degrees_to_radians(fov / 2));
            auto viewport_width = viewport_height * aspect_ratio;
            std::cerr << "viewport_height: " << viewport_height << " viewport_width: " << viewport_width << "\n";

            // The rest was generated by copilot using the code in main.cpp, 
            // though i removed the image_height section since that's not needed here

            // lookAt defines the point which the camera is looking at: to find the axis along which the camera is pointing,
            // we need to subtract the camera position from the lookAt point
            vec3 cameraForwardAxis = unit_vector(lookAt - position);
            // find rotation matrix between (0, 0, 1) and lookAt (added by me)
            double rotationForwardAxis[3][3];
            rotationMatrix(vec3(0,0,1), cameraForwardAxis, rotationForwardAxis);
            // std::cerr << "rotationLook: " << rotationLook[0][0] << " " << rotationLook[0][1] << " " << rotationLook[0][2] << "\n";
            // std::cerr << "rotationLook: " << rotationLook[1][0] << " " << rotationLook[1][1] << " " << rotationLook[1][2] << "\n";
            // std::cerr << "rotationLook: " << rotationLook[2][0] << " " << rotationLook[2][1] << " " << rotationLook[2][2] << "\n";

            // the upVector probably needs to be projected on the camera plane first: the axis defined in the file may be arbitrary
            double rotationUp[3][3];
            rotationMatrix(vec3(0,1,0), upVector, rotationUp);
            // std::cerr << "rotationUp: " << rotationUp[0][0] << " " << rotationUp[0][1] << " " << rotationUp[0][2] << "\n";
            // std::cerr << "rotationUp: " << rotationUp[1][0] << " " << rotationUp[1][1] << " " << rotationUp[1][2] << "\n";
            // std::cerr << "rotationUp: " << rotationUp[2][0] << " " << rotationUp[2][1] << " " << rotationUp[2][2] << "\n";

            // Calculate the vectors across the horizontal and down the vertical viewport edges.
            auto viewport_u = vec3(viewport_width, 0, 0) * rotationForwardAxis * rotationUp;
            auto viewport_v = vec3(0, -viewport_height, 0) * rotationForwardAxis * rotationUp;

            // Calculate the horizontal and vertical delta vectors from pixel to pixel.
            pixel_delta_u = viewport_u / width;
            pixel_delta_v = viewport_v / height;

            // Calculate the location of the upper left pixel.
            auto viewport_upper_left = position
                                    + (focal_length * lookAt) - viewport_u/2 - viewport_v/2;
            // std::cerr << "viewport_upper_left: " << viewport_upper_left << "\n";
            pixel00_loc = viewport_upper_left + 0.5 * (pixel_delta_u + pixel_delta_v);
        }

    public:
        camera() :
            width(1920), height(1080), lookAt(0, 0, 1), upVector(0, 1, 0) {}
        camera(int width, int height, point3 position, vec3 lookAt, vec3 upVector, double fov, double exposure) :
            width(width), height(height), position(position), lookAt(lookAt), upVector(upVector), fov(fov), exposure(exposure) {
                initialise();
            }

        int getWidth() { return width; }
        int getHeight() { return height; }
        point3 getPosition() { return position; }

        vec3 getPixel00Loc() { return pixel00_loc; }
        vec3 getPixelDeltaU() { return pixel_delta_u; }
        vec3 getPixelDeltaV() { return pixel_delta_v; }

        // implement the actual code from main.cpp here later

};


#endif