#ifndef CAMERA_H
#define CAMERA_H

#include "vec3.h"
#include "utility.h"

class camera {
    private:
        int width;
        int height;
        point3 position;
        vec3 lookAt;
        vec3 upVector;
        double fov;
        double exposure;

        void initialise() {
            auto focal_length = 1.0;
            auto aspect_ratio = static_cast<double>(width) / height;

            // assuming the fov is 1) in degrees, 2) referring to the vertical fov
            auto viewport_height = focal_length * tan(degrees_to_radians(fov));
            auto viewport_width = viewport_height * aspect_ratio;

            // The rest was generated by copilot using the code in main.cpp, 
            // though i removed the image_height section since that's not needed here

            // find rotation matrix between (0, 0, 1) and lookAt (added by me)
            double rotationLook[3][3];
            rotationMatrix(vec3(0,0,1), lookAt, rotationLook);

            double rotationUp[3][3];
            rotationMatrix(vec3(0,1,0), upVector, rotationUp);

            // Calculate the vectors across the horizontal and down the vertical viewport edges.
            auto viewport_u = vec3(viewport_width, 0, 0) * rotationLook * rotationUp;
            auto viewport_v = vec3(0, -viewport_height, 0) * rotationLook * rotationUp;

            // Calculate the horizontal and vertical delta vectors from pixel to pixel.
            auto pixel_delta_u = viewport_u / width;
            auto pixel_delta_v = viewport_v / height;

            // Calculate the location of the upper left pixel.
            auto viewport_upper_left = position
                                    + (focal_length * lookAt) - viewport_u/2 - viewport_v/2;
            // std::cerr << "viewport_upper_left: " << viewport_upper_left << "\n";
            auto pixel00_loc = viewport_upper_left + 0.5 * (pixel_delta_u + pixel_delta_v);
        }

    public:
        camera() :
            width(1920), height(1080), lookAt(0, 0, 1), upVector(0, 1, 0) {}
        camera(int width, int height, point3 position, vec3 lookAt, vec3 upVector, double fov, double exposure) :
            width(width), height(height), position(position), lookAt(lookAt), upVector(upVector), fov(fov), exposure(exposure) {}

        // implement the actual code from main.cpp here later

};


#endif