#ifndef POINTLIGHT_H
#define POINTLIGHT_H
#include "vec3.h"
#include "color.h"

class pointlight {
    public:
        // generated by copilot
        pointlight(point3 position, color intensity) : position(position), intensity(intensity) {}
        point3 getPosition() const { return position; }
        color getIntensity() { return intensity; }
    private:
        point3 position;
        color intensity;
};

#endif