//Create an abstract shape class with a pure virtual function called intersection
// ALL GENERATED BY COPILOT
#ifndef SHAPE_H
#define SHAPE_H

#include "ray.h"
#include "vec3.h"
#include "material.h"

class shape {
    public:
        virtual double intersection(const ray& r) const {
            std::cerr << "under no circumstances should this be fucking called ever" << std::endl;
            return -1;
        };
        virtual material get_material() const {}
        virtual vec3 get_normal(point3 point) const {}

        virtual ~shape() = default;
        
};

#endif