//Create an abstract shape class with a pure virtual function called intersection
// ALL GENERATED BY COPILOT
#ifndef SHAPE_H
#define SHAPE_H

#include "ray.h"
#include "vec3.h"

class shape {
    public:
        virtual bool intersection(const ray& r) const {
            std::cerr << "under no circumstances should this be fucking called ever" << std::endl;
            return false;
        };
        virtual ~shape() = default;
};

#endif